Fixing carapace

diff --git a/dot_config/zsh/dot_zshrc b/dot_config/zsh/dot_zshrc
--- a/dot_config/zsh/dot_zshrc
+++ b/dot_config/zsh/dot_zshrc
@@ -31,14 +31,6 @@ else
   echo "[WARN] Zoxide not found" >&2
 fi
 
-# Check Carapace installation
-if command -v carapace >/dev/null 2>&1; then
-  zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
-  source <(carapace _carapace)
-else
-  echo "[WARN] Carapace not found" >&2
-fi
-
 # Zinit setup (plugin manager)
 ZINIT_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/zinit/zinit.git"
 [ ! -d "$ZINIT_HOME" ] && mkdir -p "$(dirname "$ZINIT_HOME")"
@@ -84,3 +76,20 @@ function __bind_history_keys() {
   bindkey '^[[A' history-substring-search-up    # Up arrow
   bindkey '^[[B' history-substring-search-down  # Down arrow
 }
+
+# Check Carapace installation
+if command -v carapace >/dev/null 2>&1; then
+  zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
+  source <(carapace _carapace)
+else
+  echo "[WARN] Carapace not found" >&2
+fi
+
+# Check Carapace installation
+if command -v carapace >/dev/null 2>&1; then
+  zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
+  source <(carapace _carapace)
+else
+  echo "[WARN] Carapace not found" >&2
+fi
+
